# Generated by Django 6.0.3 on 2026-04-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_servicebooking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
