# Generated by Django 6.0.3 on 2026-04-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_servicebooking_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='transaction_id',
        ),
    ]
