# Generated by Django 6.0.3 on 2026-04-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_servicebooking_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='upi_id',
            field=models.CharField(blank=True, help_text='Workshop UPI ID for payments', max_length=100, null=True),
        ),
    ]
