# Generated by Django 6.0.3 on 2026-04-11 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_servicebooking_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='upi_id',
        ),
    ]
